# Generated by Django 3.2.25 on 2025-01-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='Event Title')),
                ('location', models.CharField(max_length=200, verbose_name='Event Location')),
                ('start_date', models.DateTimeField(verbose_name='Start Date and Time')),
                ('end_date', models.DateTimeField(verbose_name='End Date and Time')),
                ('speakers', models.TextField()),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
    ]
