# Generated by Django 3.2.25 on 2025-01-22 20:36

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Research Title')),
                ('document', models.FileField(blank=True, null=True, upload_to='research_docs/', verbose_name='Document (PDF)')),
                ('content', tinymce.models.HTMLField()),
                ('year', models.PositiveIntegerField(verbose_name='Year of Publication')),
                ('authors', models.TextField(verbose_name='Authors')),
                ('footnote', models.TextField(verbose_name='Footnote')),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_images/', verbose_name='Image')),
            ],
            options={
                'verbose_name': 'Research',
                'verbose_name_plural': 'Research Studies',
            },
        ),
    ]
