# Generated by Django 3.2.25 on 2024-11-09 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='research',
            name='authors',
            field=models.TextField(verbose_name='Authors'),
        ),
        migrations.AlterField(
            model_name='research',
            name='footnote',
            field=models.TextField(verbose_name='Footnote'),
        ),
    ]
