# Generated by Django 3.2.25 on 2025-02-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'verbose_name': 'Research Papers and Reports', 'verbose_name_plural': 'Research Papers and Reports'},
        ),
    ]
