# Generated by Django 3.2.25 on 2025-02-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('briefs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brief',
            options={'verbose_name': 'Policy Briefs', 'verbose_name_plural': 'Policy Briefs'},
        ),
    ]
