# Generated by Django 3.2.25 on 2025-02-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ['created_at'], 'verbose_name': 'Guides and Toolkits', 'verbose_name_plural': 'Guides and Toolkits'},
        ),
    ]
